# Generated by Django 2.2 on 2020-12-02 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': '案例', 'verbose_name_plural': '案例'},
        ),
    ]
