# Generated by Django 2.2 on 2020-12-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_auto_20201203_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_content',
            field=models.TextField(blank=True, null=True, verbose_name='案例内容'),
        ),
    ]
