# Generated by Django 2.2 on 2020-12-02 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': '首页', 'verbose_name_plural': '首页'},
        ),
    ]
