# Generated by Django 2.2 on 2020-12-02 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': '关于', 'verbose_name_plural': '关于'},
        ),
    ]
