# Generated by Django 2.2 on 2020-12-04 19:46

import about.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20201202_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_title',
            field=models.CharField(blank=True, default='房产快销赋能平台', max_length=255, null=True, verbose_name='案例标题'),
        ),
        migrations.AddField(
            model_name='about',
            name='activity_image',
            field=models.ImageField(default='', null=None, upload_to='about/data/', verbose_name='活动展示图片'),
        ),
        migrations.AddField(
            model_name='about',
            name='case_image',
            field=models.ImageField(default='', null=None, upload_to='about/data/', verbose_name='案例落地图片'),
        ),
        migrations.AddField(
            model_name='about',
            name='create_time',
            field=models.DateTimeField(blank=True, default=about.models.create_time, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='about',
            name='title_image',
            field=models.ImageField(default='', null=None, upload_to='about/data/', verbose_name='案例图片'),
        ),
    ]
