# Generated by Django 2.2 on 2020-12-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20201204_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='activity_image_data',
            field=models.TextField(blank=True, null=True, verbose_name='活动展示图片数据'),
        ),
        migrations.AddField(
            model_name='about',
            name='case_image_data',
            field=models.TextField(blank=True, null=True, verbose_name='案例落地图片数据'),
        ),
        migrations.AddField(
            model_name='about',
            name='titile_image_data',
            field=models.TextField(blank=True, null=True, verbose_name='头图片数据'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title_image',
            field=models.ImageField(default='', null=None, upload_to='about/data/', verbose_name='头图片'),
        ),
    ]
